# Generated by Django 5.0.1 on 2024-09-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': False, 'ordering': ['user'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
