# Generated by Django 5.0.1 on 2024-09-23 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='perfiles',
        ),
    ]
