# Generated by Django 5.0.1 on 2024-12-27 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0029_alter_naturalezahallazgo_table'),
        ('usuarios', '0003_alter_profile_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(db_column='area', on_delete=django.db.models.deletion.CASCADE, to='syh.area')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Área de Perfil',
                'verbose_name_plural': 'Áreas de Perfiles',
                'ordering': ['user'],
            },
        ),
    ]
