# Generated by Django 5.0.1 on 2025-01-11 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syh', '0029_alter_naturalezahallazgo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('anio', models.IntegerField()),
                ('baja', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syh.cliente')),
            ],
            options={
                'verbose_name': 'Movil',
                'verbose_name_plural': 'Moviles',
                'db_table': 'moviles',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='Vencimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimiento', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviles.movil')),
            ],
            options={
                'verbose_name': 'Vencimiento',
                'verbose_name_plural': 'Vencimientos',
                'db_table': 'vencimientos',
                'ordering': ['vencimiento'],
            },
        ),
    ]
