# Generated by Django 5.0.1 on 2025-01-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movil',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vencimientos',
            table=None,
        ),
    ]
