# Generated by Django 5.0.1 on 2025-01-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0002_alter_movil_table_alter_vencimientos_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVencimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Vencimiento',
                'verbose_name_plural': 'Tipos de Vencimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='vencimientos',
            options={'ordering': ['-fecha', 'tipo_vencimiento'], 'verbose_name': 'Vencimiento', 'verbose_name_plural': 'Vencimientos'},
        ),
        migrations.RenameField(
            model_name='vencimientos',
            old_name='vencimiento',
            new_name='detalle',
        ),
        migrations.AddField(
            model_name='vencimientos',
            name='tipo_vencimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moviles.tipovencimientos'),
        ),
    ]
