# Generated by Django 5.0.1 on 2025-01-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0003_tipovencimientos_alter_vencimientos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipovencimientos',
            name='tipo',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Moviles', 'Moviles')], default='Personal', max_length=50),
        ),
    ]
