# Generated by Django 5.0.1 on 2025-01-14 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0004_tipovencimientos_tipo'),
        ('syh', '0029_alter_naturalezahallazgo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('cuit', models.CharField(max_length=13)),
                ('baja', models.BooleanField(default=False)),
                ('fecha_cumpleanios', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syh.cliente')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
