# Generated by Django 5.0.1 on 2025-01-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0005_personal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='fecha_cumpleanios',
            new_name='fecha_nacimiento',
        ),
    ]
