# Generated by Django 5.0.1 on 2025-01-14 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0006_rename_fecha_cumpleanios_personal_fecha_nacimiento'),
        ('syh', '0029_alter_naturalezahallazgo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_hora', models.IntegerField(verbose_name='Km/Hora')),
                ('tipo_combustible', models.CharField(choices=[('Super', 'Super'), ('Infinia Nafta', 'Infinia Nafta'), ('Ultra', 'Ultra'), ('Infinia Diesel', 'Infinia Diesel'), ('Urea', 'Urea')], default='Ultra', max_length=50)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syh.cliente')),
                ('movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviles.movil')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviles.personal')),
            ],
            options={
                'verbose_name': 'Carga de Combustible',
                'verbose_name_plural': 'Cargas de Combustible',
                'ordering': ['-fecha'],
            },
        ),
    ]
