# Generated by Django 5.0.1 on 2025-01-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0007_cargacombustible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargacombustible',
            old_name='personal',
            new_name='chofer',
        ),
    ]
