# Generated by Django 5.0.1 on 2025-01-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0008_rename_personal_cargacombustible_chofer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargacombustible',
            old_name='cliente',
            new_name='empresa',
        ),
    ]
