# Generated by Django 5.0.1 on 2025-04-24 11:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0009_rename_cliente_cargacombustible_empresa'),
        ('syh', '0031_delete_matafuegos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matafuegos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_interno', models.CharField(default='', max_length=20)),
                ('fecha_vencimiento', models.DateField(default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField(default=0)),
                ('ubicacion', models.CharField(default='', max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('capacidad', models.IntegerField(default=0)),
                ('baja', models.BooleanField(default=False)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('mail_responsable', models.EmailField(blank=True, max_length=254, null=True)),
                ('area', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='syh.area')),
                ('cliente', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='syh.cliente')),
            ],
            options={
                'verbose_name': 'Matafuegos',
                'verbose_name_plural': 'Matafuegos',
            },
        ),
    ]
