# Generated by Django 5.0.1 on 2025-07-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0010_matafuegos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matafuegos',
            name='observaciones',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
