# Generated by Django 5.0.1 on 2025-07-31 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0011_alter_matafuegos_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Centro de Costos',
                'verbose_name_plural': 'Centros de Costos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='GastosMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('centro_costos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviles.centrocostos')),
                ('movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviles.movil')),
            ],
            options={
                'verbose_name': 'Gasto de Movil',
                'verbose_name_plural': 'Gastos de Movil',
                'ordering': ['-fecha'],
            },
        ),
    ]
