# Generated by Django 5.0.1 on 2025-07-31 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0012_centrocostos_gastosmovil'),
        ('syh', '0031_delete_matafuegos'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosmovil',
            name='cliente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='syh.cliente'),
        ),
    ]
