# Generated by Django 5.0.1 on 2025-07-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0013_gastosmovil_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosmovil',
            name='comprobante',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
