# Generated by Django 5.0.1 on 2025-08-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0014_gastosmovil_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosmovil',
            name='litros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
