# Generated by Django 5.1.1 on 2025-08-09 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0015_gastosmovil_litros'),
        ('syh', '0031_delete_matafuegos'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosmovil',
            name='area',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='syh.area'),
        ),
    ]
