# Generated by Django 5.1.1 on 2025-08-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0016_gastosmovil_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosmovil',
            name='km_hora',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
