# Generated by Django 5.0.1 on 2025-09-30 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0017_gastosmovil_km_hora'),
        ('syh', '0031_delete_matafuegos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Predio',
                'verbose_name_plural': 'Predios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('destino', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=100)),
                ('tn_pulpable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tn_aserrable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tn_chip', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sin_actividad', models.BooleanField(default=False)),
                ('motivo_sin_actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='syh.area')),
                ('cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='syh.cliente')),
                ('movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviles.movil')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen_predio', to='moviles.predios')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-fecha', 'movil'],
            },
        ),
    ]
