# Generated by Django 5.0.1 on 2025-09-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0018_predios_viajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='record_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
