# Generated by Django 5.0.1 on 2025-10-03 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0019_viajes_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moviles.personal'),
        ),
    ]
