# Generated by Django 5.0.1 on 2024-09-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(default='', max_length=30)),
                ('valor', models.CharField(default='', max_length=80)),
                ('detalle', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Parámetros del sistema',
                'db_table': 'parametro_sistema',
            },
        ),
    ]
