# Generated by Django 5.0.1 on 2024-09-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0002_parametrosistema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosistema',
            name='id',
        ),
        migrations.AlterField(
            model_name='parametrosistema',
            name='parametro',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
