# Generated by Django 5.0.1 on 2024-09-23 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0003_remove_parametrosistema_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('detalle', models.TextField()),
                ('archivo', models.ImageField(upload_to='media/evidencias/')),
                ('movimiento', models.ForeignKey(db_column='movimiento', on_delete=django.db.models.deletion.CASCADE, to='syh.movimientos')),
            ],
        ),
    ]
