# Generated by Django 5.0.1 on 2024-09-23 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0004_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 9, 23, 18, 7, 37, 568283)),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
