# Generated by Django 5.0.1 on 2024-09-24 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0005_alter_evidencia_fecha_alter_evidencia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='archivo',
            field=models.ImageField(blank=True, upload_to='evidencias/'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
