# Generated by Django 5.0.1 on 2024-10-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0006_alter_evidencia_archivo_alter_evidencia_detalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmisionCarbono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='', max_length=80)),
                ('fe', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='FE (CO2/litro)')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad consumida')),
            ],
        ),
    ]
