# Generated by Django 5.0.1 on 2024-10-10 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0007_emisioncarbono'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisioncarbono',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='syh.cliente'),
        ),
    ]
