# Generated by Django 5.0.1 on 2024-10-10 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0008_emisioncarbono_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisioncarbono',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emisioncarbono',
            name='periodo',
            field=models.CharField(blank=True, editable=False, max_length=7),
        ),
    ]
