# Generated by Django 5.0.1 on 2024-10-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0009_emisioncarbono_fecha_emisioncarbono_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisioncarbono',
            name='tipo',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Nafta', 'Nafta'), ('Aceite para Motores', 'Aceite para Motores'), ('Aceite Hidráulico', 'Aceite Hidráulico'), ('Aceite Lubricantes de Cadena', 'Aceite Lubricantes de Cadena')], default='', max_length=80),
        ),
    ]
