# Generated by Django 5.0.1 on 2024-10-10 19:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0010_alter_emisioncarbono_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabeceraLCO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('tipo', models.CharField(choices=[('Transporte', 'Transporte'), ('Dormitorios', 'Dormitorios'), ('Comedores', 'Comedores'), ('Baños y vestuarios', 'Baños y vestuarios'), ('Moviles', 'Moviles'), ('Caminos', 'Caminos'), ('Otros', 'Otros')], default='', max_length=80)),
                ('cliente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='syh.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleLCO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_lco', models.CharField(default='', max_length=100)),
                ('cabecera_lco', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='syh.cabeceralco')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientosLCO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_lco', models.DateField(default=django.utils.timezone.now)),
                ('plazo', models.IntegerField(default=0)),
                ('cumplimiento', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('NA', 'NA')], default='', max_length=80)),
                ('observaciones', models.CharField(default='', max_length=250)),
                ('detalle_lco', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='syh.detallelco')),
            ],
        ),
    ]
