# Generated by Django 5.0.1 on 2024-10-10 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0011_cabeceralco_detallelco_movimientoslco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabeceralco',
            name='cliente',
        ),
        migrations.AddField(
            model_name='movimientoslco',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='syh.cliente'),
        ),
    ]
