# Generated by Django 5.0.1 on 2024-10-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0012_remove_cabeceralco_cliente_movimientoslco_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabeceralco',
            name='tipo',
            field=models.CharField(choices=[('Transporte', 'Transporte'), ('Dormitorios', 'Dormitorios'), ('Comedores', 'Comedores'), ('Baños y vestuarios', 'Baños y vestuarios'), ('Moviles', 'Moviles'), ('Caminos', 'Caminos'), ('Otros', 'Otros')], default='', max_length=200),
        ),
    ]
