# Generated by Django 5.0.1 on 2024-10-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0013_alter_cabeceralco_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabeceralco',
            name='tipo',
        ),
    ]
