# Generated by Django 5.0.1 on 2024-10-12 12:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0014_remove_cabeceralco_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoslco',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='movimientoslco',
            name='fecha_lco',
        ),
        migrations.CreateModel(
            name='CabMovLCO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_lco', models.DateField(default=django.utils.timezone.now)),
                ('cabecera_lco', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='syh.cabeceralco')),
                ('cliente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='syh.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='movimientoslco',
            name='cabecera_lco',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='syh.cabmovlco'),
        ),
    ]
