# Generated by Django 5.0.1 on 2024-10-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0015_remove_movimientoslco_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabmovlco',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('CERRADO', 'CERRADO')], default='PENDIENTE', max_length=80),
        ),
    ]
