# Generated by Django 5.0.1 on 2024-10-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0016_cabmovlco_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallelco',
            name='cumplimiento',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('NA', 'NA')], default='', max_length=80),
        ),
    ]
