# Generated by Django 5.0.1 on 2024-10-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0017_detallelco_cumplimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoslco',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
