# Generated by Django 5.0.1 on 2024-10-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0018_alter_movimientoslco_observaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoslco',
            options={'ordering': ['cabecera_lco', 'detalle_lco'], 'verbose_name': 'Movimiento LCO', 'verbose_name_plural': 'Movimientos LCO'},
        ),
        migrations.AddField(
            model_name='movimientoslco',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='movimientoslco',
            table='movimientos_lco',
        ),
    ]
