# Generated by Django 5.0.1 on 2024-10-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0019_alter_movimientoslco_options_movimientoslco_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movimientoslco',
            table=None,
        ),
    ]
