# Generated by Django 5.0.1 on 2024-10-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0020_alter_movimientoslco_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallelco',
            name='observaciones',
            field=models.CharField(default='', max_length=100),
        ),
    ]
