# Generated by Django 5.0.1 on 2024-10-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0021_detallelco_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallelco',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoslco',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
