# Generated by Django 5.0.1 on 2024-10-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0022_alter_detallelco_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallelco',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
