# Generated by Django 5.0.1 on 2024-10-18 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0023_detallelco_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceAccidentabilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(default=0)),
                ('mes', models.IntegerField(default=0)),
                ('ACTP', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Accidentes con Tiempo Perdido (ACTP)')),
                ('ASTP', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Accidentes Sin Tiempo Perdido (ASTP)')),
                ('TPA', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tiempo Perdido por Accidente (TPA)')),
                ('personal', models.IntegerField(default=0, verbose_name='Número Total de Trabajadores (T)')),
                ('hrs_hombres', models.IntegerField(default=0, verbose_name='Total de Horas Hombre (HH)')),
                ('cliente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='syh.cliente')),
            ],
            options={
                'verbose_name': 'Indice de Accidentabilidad',
                'verbose_name_plural': 'Indices de Accidentabilidad',
            },
        ),
    ]
