# Generated by Django 5.0.1 on 2024-10-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0024_indiceaccidentabilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiceaccidentabilidad',
            name='anio',
            field=models.IntegerField(default=0, verbose_name='Año'),
        ),
    ]
