# Generated by Django 5.0.1 on 2024-10-18 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0025_alter_indiceaccidentabilidad_anio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcesosVelocidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(default=0, verbose_name='Año')),
                ('mes', models.IntegerField(default=0)),
                ('semana', models.IntegerField(default=0)),
                ('excesos', models.IntegerField(default=0)),
                ('area', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='syh.area')),
                ('cliente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='syh.cliente')),
            ],
            options={
                'verbose_name': 'Excesos de Velocidad',
                'verbose_name_plural': 'Excesos de Velocidad',
            },
        ),
    ]
