# Generated by Django 5.0.1 on 2024-10-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0026_excesosvelocidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excesosvelocidad',
            name='area',
        ),
    ]
