# Generated by Django 5.0.1 on 2024-12-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0027_remove_excesosvelocidad_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalezaHallazgo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naturaleza', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Naturaleza Hallazgo',
                'verbose_name_plural': 'Naturaleza Hallazgos',
                'db_table': 'naturaleza_hallazgo',
                'ordering': ['naturaleza'],
            },
        ),
    ]
