# Generated by Django 5.0.1 on 2024-12-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0028_naturalezahallazgo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='naturalezahallazgo',
            table=None,
        ),
    ]
