# Generated by Django 5.0.1 on 2025-04-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syh', '0030_matafuegos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matafuegos',
        ),
    ]
